services:
  app:
    build: .
    container_name: concrete_app_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:1.27-alpine
    container_name: concrete_app_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
